@hostname=localhost
@port=7245
@host={{hostname}}:{{port}}
@flightdirector = flightdirector

###
GET https://{{host}}/{{flightdirector}}/1/4

###
POST https://{{host}}/{{flightdirector}}
Content-Type: application/json
Accept-Language: en-US,en;q=0.5

{
    "date": "2023-05-10",
    "temperatureC": 30,
    "summary": "Warm"
}