@hostname=localhost
@port=7245
@host={{hostname}}:{{port}}
@flight = flight

###
GET https://{{host}}/{{flight}}/1/4

###
POST https://{{host}}/{{flight}}/buyticket
Content-Type: application/json

{
    "flightId": {
      "value": "34ffca8e-65ea-425e-87df-1eed9b402ce7"
    },
    "dateOfBirth": "2023-08-10",
    "gender": 1,
    "firstName": "Ivan",
    "lastName": "Cavlek",
    "seat": 1
}