@hostname=localhost
@port=7245
@host={{hostname}}:{{port}}
@fleet = fleet
@airplane = airplane

###
POST https://{{host}}/{{fleet}}/{{airplane}}
Content-Type: application/json

{
    "type": 2,
    "configuration": 1,
    "country": 0,
    "airplaneRegistration": "D-A123"
}

###
GET https://{{host}}/{{fleet}}/{{airplane}}?airplaneid=8a00a47b-de1a-07e9-85b6-3a0e55521804&airplaneregistration=D-A123

###
GET https://{{host}}/{{fleet}}

###
PUT https://{{host}}/{{fleet}}/{{airplane}}
Content-Type: application/json

{
    "airplaneid": "8a00a47b-de1a-07e9-85b6-3a0e55521804",
    "configuration": 2,
    "airplaneRegistration": "D-A123"
}

###
DELETE https://{{host}}/{{fleet}}/{{airplane}}?airplaneid=8a00a47b-de1a-07e9-85b6-3a0e55521804&airplaneregistration=D-A123